# Generated by Django 5.1.1 on 2024-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('descuentoBool', models.BooleanField(default=False)),
            ],
        ),
    ]
